### ISSUE TITLE
Difference with Sagemath (& Manifold)

### ISSUE THREAD

**Issue by scollovati** [miguelgondu/generalrepytivity#1]
Hi, 
I was wondering why are you developing your own Python code for tensor calculus in GR.
In the last months I started using Sagemath which has a lot of functionalities already built in.
Of course If you need to use just the manifold part you have to install the whole software, which may be annoying. :)

**Comment by miguelgondu** [comment]
Hi,

I'm aware of Sagemath (and sympy's library on differential geomertry) but, and this may be because I haven't read them that much, I felt that some of the purely algebraic aspects were missing. I just wanted to create a small code in which you could manipulate indices easier and in which you could have this black box that computes Christoffel Symbols and the usual suspects (Riemman, Ricci, scalar curvature) just from the metric. 

Of course, it is small and amateur-ish, so any help is more than welcomed. Nowadays I'm thinking of a way of *inflicting less pain* to its users: having to create a dictionary of values and having to explicity pass the $(p,q)$ seems rather convoluted, and I'm yet to write a decent tutorial. [Here's a blogpost in which I used it for some small calculations](https://miguelgondu.github.io/math/python/2018/01/18/A-couple-of-metrics-in-generalrepytivity.html).

**Comment by scollovati** [comment]
Thank you for the answer!
I completely understand your point, I'm always interested in knowing different point of views.

I think that your library is a really good starting point and I agree that the setup of the tensors (especially the metric one) as it is implemented now is not so easy.
